name: build

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, test and build
        run: |
          npm install
          npm test
          npm build
        env:
          CI: true
